### ISSUE TITLE
Apple-ID mit 2FA nicht unterstützt?

### ISSUE THREAD

**Issue by ruhr70** [soef/ioBroker.find-my-iphone#3]
Version 0.0.5 

Über Admin/Adapter installiert. OK.
Apple-ID wird erkannt.

2FA funktioniert leider nicht oder ich weiss nicht wie.

Anhand der Apple-ID wird erkannt, das Zweifaktorauthentifizierung (2FA) aktiv ist.
Bei Bestätigung über eins der Apple Geräte werde ich von diesem auch gebeten, den 6-stelligen Code bei der App einzugeben. Da sehe ich beim Adapter nur keine Möglichkeit.

**Comment by charlphyro** [comment]
Hallo,
Habe auch die 2FA und bei mir funktioniert es.
Im IoBroker den Adapter Installiert und das iCloud Passwort eingegeben, dass alles am iPad direkt.
Nach dem Speicher und schließen, ist die Anfrage auch am iPad erschienen, erlauben bestätigt.
In den Objekten werden alle meine Geräte angezeigt.

**Comment by ruhr70** [comment]
Ist das die alte oder die neue 2FA Variante von Apple?

Ich habe auf die aktuelle Variante umgestellt. Da reicht Bestätigen nicht, sondern man muss noch in der anfragenden App einen 6-stelliugen Code eingeben. Ich konnte jedenfalls nichts einfach bestätigen.

**Comment by ruhr70** [comment]
shit...

Wenn man sich mit Github nicht auskennt ;-)
sollte nciht geschlossen werden. Reopen.

**Comment by xfjx** [comment]
Wer das "neue" 2FA von Apple aktiviert hat:

Step 1: mit iCloud Kennwort im Adapter anmelden
Step 2: Anmeldung auf irgendeinem Gerät bestätigen 
Step 3: das Kennwort im Adapter ändern und einfach den 6stelligen Code HINTEN DRAN HÄNGEN
Step 4: es gibt keinen Step 4!

Das geht übrigens bei allen Apps usw. die 2FA nicht unterstützen.

**Comment by xfjx** [comment]
Wäre vielleicht was für die Doku?

**Comment by soef** [comment]
Hallo, vielen Dank für die Info.  Hab' es in die Readme und in die Konfiguration übernommen.
